### ISSUE TITLE
Toast not defined issue

### ISSUE THREAD

**Issue by CanRau** [pyrsmk/toast#12]
Thanks for this nice little helper!
Got a little issue with console saying "Toast not defined"

After changing L134 to return toast; it's working now :)

**Comment by pyrsmk** [comment]
Thanks for the report! I don't know how this has happened.The problem comes from the new UMD wrapper bad configured in the gulpfile. Moreover, the old UMD wrapper is still present in the source.

I'm fixing that right away.

**Comment by CanRau** [comment]
Great, thanks :)
