### ISSUE TITLE
toast.js ==> Toast.js

### ISSUE THREAD

**Issue by soguagirl** [pyrsmk/toast#24]
![image](https://user-images.githubusercontent.com/7897851/88992111-0fbc6400-d315-11ea-89e8-26a75289698a.png)

**Comment by pyrsmk** [comment]
Indeed. There was a problem with the last release where two versions of the same file collided. I fixed by deleting one of the files, but it seems I removed the wrong one.

I'm fixing this ASAP.

edit: when I say "same files", I mean "same files with same filename but different case"

**Comment by pyrsmk** [comment]
Just pushed a new version : `3.0.4`.

I renamed the file by `toast.umd.js` to avoid further new collisions with `Toast.js`. Since the package.json's `main` property has been updated accordingly, it should work as expected.

Please update and let me know if everything is good ;)

**Comment by pyrsmk** [comment]
Without further response from you, I consider this issue fixed. Please reopen if not.

**Comment by soguagirl** [comment]
ok, thx
